version: "3.7"

services:

  app-url-shortener:
    build:
      context: .
      dockerfile: ./python/Dockerfile
      target: debug
    container_name: app-url-shortener
    entrypoint: [ "python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "app", 
      "--wait-for-client", "--multiprocess", "-m", "flask", "run", "-h", "0.0.0.0", "-p", "3031" 
    ]
    environment:
      - FLASK_DEBUG=1
    ports:
      - 5678:5678
    volumes:
      - ./app/:/home/url-shortener-user/app
    restart: unless-stopped

  nginx-url-shortener:
    image: nginx:1.21
    container_name: nginx-url-shortener
    restart: unless-stopped
    depends_on:
      - app-url-shortener
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"