version: "3.7"

networks:
  url-shortener-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16

services:
  app-url-shortener:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
      target: debug
    container_name: app-url-shortener
    ports:
      - 5678:5678 # port for debugpy
    volumes:
      - ./app:/home/url-shortener-user/app
    depends_on:
      - db-url-shortener
    env_file:
      - ./docker/.env
    restart: unless-stopped
    networks:
      url-shortener-net:
        ipv4_address: 10.10.0.10

  nginx-url-shortener:
    image: nginx:1.21
    container_name: nginx-url-shortener
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
        url-shortener-net:
          ipv4_address: 10.10.0.11

  db-url-shortener:
    image: postgres:13
    container_name: db-url-shortener
    restart: unless-stopped
    volumes:
      - ./docker/postgres/data/:/var/lib/postgresql/data/
    ports:
      - 5432:5432 # for DBeaver connection
    env_file:
      - ./docker/.env
    networks:
        url-shortener-net:
          ipv4_address: 10.10.0.12