version: "3.7"

services:

  app-url-shortener:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
      target: debug
    container_name: app-url-shortener
    ports:
      - 5678:5678
    volumes:
      - ./app:/home/url-shortener-user/app
    depends_on:
      - db-url-shortener
    env_file:
      - ./docker/.env
    restart: unless-stopped

  nginx-url-shortener:
    image: nginx:1.21
    container_name: nginx-url-shortener
    restart: unless-stopped
    depends_on:
      - app-url-shortener
    volumes:
      - ./docker/nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  db-url-shortener:
    image: postgres:13
    container_name: db-url-shortener
    restart: unless-stopped
    volumes:
      - ./docker/postgres/data/:/var/lib/postgresql/data/
    user: 1000:1000 # fixed problem with systemd-coredump(999-user) from image
    ports:
      - 5432:5432 # for DBeaver connection
    env_file:
      - ./docker/.env