version: "3.7"

services:

  app-url-shortener:
    build:
      context: .
      dockerfile: ./python/Dockerfile
      target: prod
    container_name: app-url-shortener
    volumes:
      - ./app/:/home/url-shortener-user/app
    restart: unless-stopped

  nginx-url-shortener:
    image: nginx:1.21
    container_name: nginx-url-shortener
    restart: unless-stopped
    depends_on:
      - app-url-shortener
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"